apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-hao-setting
spec:
  forms:
    - group: nav
      label: 导航
      formSchema:
        - $formkit: menuRadio
          name: left_menu
          label: 导航栏左侧相关链接
        - $formkit: radio
          name: right_menu
          label: 右上角四个按钮
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: text
          name: site_title
          label: 标题
          placeholder: 请输入标题
          help: '支持 HTML 语法，比如 <i class="iconfont icon-logo-hao-pro" style="font-size: 1rem"></i>，留空为站点名称'
    - group: top
      label: 顶部
      formSchema:
        - $formkit: radio
          name: recent_top
          label: 首页顶部
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: radio
          name: moment
          label: 说说模块
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: text
          name: banners_title_big
          label: Banners 大标题
          placeholder: 请输入大标题
          help: 支持 HTML 语法
        - $formkit: text
          name: banners_title_small
          label: Banners 小标题
          placeholder: 请输入小标题
          help: 支持 HTML 语法
        - $formkit: url
          name: bikan
          label: 必看精选
          placeholder: 请输入地址
          validation: "url"
        - $formkit: url
          name: remen
          label: 必看精选
          placeholder: 请输入地址
          validation: "url"
        - $formkit: url
          name: shiyong
          label: 必看精选
          placeholder: 请输入地址
          validation: "url"
        - $formkit: radio
          name: todayRecommend
          label: 今日推荐
          value: false
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false
        - $formkit: url
          name: todayRecommendUrl
          label: 今日推荐跳转地址
          placeholder: 请输入地址
          validation: "url"
        - $formkit: text
          name: todayRecommendTitle
          label: 今日推荐标题
          placeholder: 请输入标题
          value: "今日推荐"
        - $formkit: url
          name: todayRecommendCover
          label: 今日推荐背景图
          placeholder: 请输入地址
          validation: "url"
    - group: layout
      label: 布局
      formSchema:
        - $formkit: select
          name: cols
          label: 文章列表布局
          value: col2
          options:
            - label: 单列
              value: col1
            - label: 两列
              value: col2
            - label: 三列
              value: col3
            - label: 四列
              value: col4
          help: "建议单列时，将图片放在左右"
        - $formkit: select
          name: post_location
          label: 封面位置
          value: top
          options:
            - label: 上方
              value: top
            - label: 左侧
              value: left
            - label: 右侧
              value: right
            - label: 交替
              value: alternate
        - $formkit: url
          name: post_random_img
          label: 博客封面随机 API
          validation: "url"
          value: "https://source.unsplash.com/random/600x400/?blog,scenery,night,desert,sea"
          help: 二次元随机图地址：https://www.dmoe.cc/random.php    默认随机封面图 url 不能保证一直可用
    - group: sidebar
      label: 侧栏
      formSchema:
        - $formkit: select
          name: location
          label: 侧边栏位置
          value: "right-aside"
          options:
            - value: "hide-aside"
              label: "隐藏"
            - value: "right-aside"
              label: "右侧"
            - value: "left-aside"
              label: "左侧"
        - $formkit: textarea
          name: widgets
          label: 小部件
          value: "profile,wechat,comments,recent-posts,categories,tags-stat"
          help: "目前提供的小部件有：profile（站点资料）, wechat（微信）, recent-posts（近期文章）, comments（最新评论）, categories（文章分类）, tags（文章标签）, stat（统计）, tags-stat（标签&统计）。你可以随意组合或排序，以逗号隔开。"
        - $formkit: textarea
          name: post_widgets
          label: 文章页面小部件
          value: "profile,wechat,toc,comments,recent-posts,categories,tags-stat"
          help: "post 可以支持设置 toc "
        - $formkit: textarea
          name: tag_widgets
          label: 标签页面小部件
          value: "profile,wechat,comments,recent-posts,categories,tags-stat"
        - $formkit: textarea
          name: category_widgets
          label: 分类页面小部件
          value: "profile,wechat,comments,recent-posts,categories,tags-stat"
        - $formkit: textarea
          name: page_widgets
          label: 自定义页面小部件
          value: ""
        - $formkit: text
          name: profile_name
          label: 个人卡片名称
          placeholder: 请填写个人卡片名称
          help: "不填写默认为站点则名称"
        - $formkit: textarea
          name: profile_desc
          placeholder: 请填写个人卡片描述信息
          help: "支持使用 HTML 标签"
        - $formkit: url
          name: wechat_img_face
          placeholder: 微信正面图
          validation: "url"
        - $formkit: url
          name: wechat_img_back
          placeholder: 微信背面图
          validation: "url"
          help: 图片可以从公众号后台下载物料或者自制
    - group: footer
      label: 页脚
      formSchema:
        - $formkit: textarea
          name: social
          label: 社交链接（无效）
          placeholder: 暂时不支持配置
          help: "当前版本不支持配置"
        - $formkit: menuRadio
          name: menu
          label: 底部相关链接
        - $formkit: text
          name: copyright_start
          label: 开始时间
          placeholder: 建站时间
          help: "copyright 开始时间"
        - $formkit: text
          name: icp
          label: ICP 备案
          placeholder: 请输入 ICP 备案号
          help: "京ICP备xxxxxxxx号"
    - group: post
      label: 文章
      formSchema:
        - $formkit: radio
          name: copyright
          label: 版权声明
          value: true
          options:
            - label: 打开
              value: true
            - label: 关闭
              value: false
          help: "文章底部显示版权声明模块"
        - $formkit: url
          name: copyrightAgreement
          label: 版权协议
          placeholder: "请输入版权协议地址"
        - $formkit: textarea
          name: copyrightInfo
          label: 版权声明
          placeholder: '本文是原创文章，采用 <a target="_blank" href="/cc">CC BY-NC-ND 4.0</a> 协议，完整转载请注明来自 <a href="/" target="_blank" >程序员小航</a>'
          help: "版权声明内容，支持填入 HTML 标签"
    - group: rightMenu
      label: 右键菜单
      formSchema:
        - $formkit: radio
          name: switch
          label: 开关
          value: false
          options:
            - label: 打开
              value: true
            - label: 关闭
              value: false
    - group: other
      label: 其他设置
      formSchema:
        - $formkit: radio
          name: loading_box
          label: 加载页
          value: true
          options:
            - label: 打开
              value: true
            - label: 关闭
              value: false
        - $formkit: url
          name: loading_box_img
          validation: "url"
          label: 加载页图片 URL
          placeholder: 请输入图片 url
        - $formkit: radio
          name: load_progress_bar
          label: 页面加载进度条
          value: true
          help: 了解更多：https://codebyzach.github.io/pace/
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false